### ISSUE TITLE
Create a snowdrop-spring-boot-dependencies bom

### ISSUE THREAD

**Issue by ebullient** [snowdrop/spring-boot-bom#62]
It is my understanding (ready to stand corrected!) that creating a spring boot application that uses the snowdrop bom follows [this expected pattern](https://access.redhat.com/documentation/en-us/red_hat_openshift_application_runtimes/1/html/spring_boot_2.1.x_runtime_guide/configuring-your-application-to-use-spring-boot_spring-boot): 

```
<project>
  ...
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>me.snowdrop</groupId>
        <artifactId>spring-boot-bom</artifactId>
        <version>2.1.6.SP3-redhat-00001</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  ...
</project>
```

The problem with dependency imports is that it doesn't apply to plugins.

In the appsody stack, I've opted to use the [spring-boot-dependencies pom](https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.1.6.RELEASE/spring-boot-dependencies-2.1.6.RELEASE.pom) as the parent (it introduces no behavior, but does pin versions using property values). While I know a lot of people don't like parent poms, it does make sense for the relationship between an appsody stack and its related/managed/dependent projects.

Bearing Andy Wilkinson's naming conventions in mind, is there a way to split this bom into two pieces: a snowdrop-spring-boot-dependencies pom, and then the snowdrop-spring-boot-bom that can use those dependencies (which then has the release profile in it, etc.)

My goal would be to switch the parent pom for a snowdrop-based stack from the "generic" spring-boot-dependencies to a "snowdrop-spring-boot-dependencies". And the only difference between them should be the values of version variables, and the addition of any dependencies or plugins that might be missing.

**Comment by gytis** [comment]
Thanks for the request, Erin. You're correct, so far this is a way to use our `spring-boot-bom`. The main reason being that we only support a subset of the dependencies and no plugins.

I cannot promise you anything at the moment, because such a parent would require an extra maintenance effort from the whole team. But we have a team meeting scheduled on Monday, so I'll make sure to raise the issue there and will get back to you ASAP.

**Comment by gytis** [comment]
Just wanted to post an update here since it has been a while since the last communication. The latest proposed version on the BOM change is available here https://github.com/snowdrop/spring-boot-bom/pull/70.

The main argument agains it was the lack of comments in the generated BOM. I would like to reiterate that the comments would still be available in GitHub and would only be removed from a file that is pushed to Maven Central.

Does anybody have any other arguments agains the use of flattening plugin or any other proposed changes other than the lack of comments? @cmoulliard @geoand  @metacosm @aureamunoz @iocanel

**Comment by geoand** [comment]
I don't and honestly for me the lack of comments is not a problem.

**Comment by ebullient** [comment]
I can try it. I just needed a poke to do so. =)

**Comment by cmoulliard** [comment]
Before to take a decision, we need at least to have some tests results to compare if the dependency:tree using it will be different vs not using it. Can you make such a comparison @gytis @ebullient ?

**Comment by gytis** [comment]
@cmoulliard as asked I did some comparisons with the current and proposed bom/parent. The latest version is here https://github.com/snowdrop/spring-boot-bom/blob/spring-boot-parent-poc-v2/pom.xml. And in this gist you can see how it would look once pushed to a maven repository: https://gist.github.com/gytis/3757b5299e1ee23bb817a09d5a043d2a.

First of all, I've rebased POC branch to have the latest BOM commits. And then I tried HTTP REST example and generated dependency trees with different boms.

Here you can see pom.xml comparison between two approaches in the example application: https://github.com/gytis/rest-http-example/compare/sb-2.1.x...gytis:sb-2.1.x-snowdrop-dependencies#diff-600376dffeb79835ede4a0b285078036.

Dependency trees are available here: https://github.com/gytis/rest-http-example/tree/sb-2.1.x-snowdrop-dependencies. As you can see they are virtually the same. The only differences are:
1. More recent maven-dependency-plugin version
2. spring-boot-devtools becomes optional
3. More recent rest-assured version

**Comment by cmoulliard** [comment]
Many thanks @gytis. Great job :-) 
If the result of the comparison are cosmetics (see previous comment), then I propose that we adopt it. Do you agree @metacosm @ebullient @geoand ?

**Comment by cmoulliard** [comment]
> Do you agree

@gytis Can you also reply ?

**Comment by gytis** [comment]
@cmoulliard reply to what? I'm the one who proposed the changes, so of course I agree with them :)

**Comment by gytis** [comment]
I've pushed the new BOM format to `sb-2.2.x` branch (https://github.com/snowdrop/spring-boot-bom/commit/6e3f6b95973aca5a4acc29e1611500dc248dc46a). I'll create the followup tasks shortly.
